import SwiftUI

/// The continent silhouettes the repeat queue decorates its rows with.
///
/// The shapes are the app's own geodata — the same Natural Earth source the
/// details map draws countries from, grouped by continent and keyed by the
/// region decks' codes. Generated by
/// `ios/Scripts/generate-continent-silhouettes.py`; a deck without a
/// silhouette — the curated ones — simply shows none.
struct ContinentSilhouettes: Sendable {
    static let shipped = ContinentSilhouettes()

    private let rings: [String: [[[Double]]]]

    init(bundle: Bundle = .module) {
        guard
            let url = bundle.url(forResource: "ContinentSilhouettes", withExtension: "json"),
            let data = try? Data(contentsOf: url),
            let decoded = try? JSONDecoder().decode([String: [[[Double]]]].self, from: data)
        else {
            rings = [:]
            return
        }
        rings = decoded
    }

    /// The region's landmasses as unit-space rings, fitted to a box whose
    /// aspect matches the shape, latitude flipped into screen order and
    /// longitude scaled by the middle latitude so the north does not smear.
    func silhouette(forDeckCode code: String) -> Silhouette? {
        guard let raw = rings[code], !raw.isEmpty else { return nil }

        var minimumLongitude = raw[0][0][0]
        var maximumLongitude = minimumLongitude
        var minimumLatitude = raw[0][0][1]
        var maximumLatitude = minimumLatitude
        for ring in raw {
            for point in ring {
                minimumLongitude = min(minimumLongitude, point[0])
                maximumLongitude = max(maximumLongitude, point[0])
                minimumLatitude = min(minimumLatitude, point[1])
                maximumLatitude = max(maximumLatitude, point[1])
            }
        }

        let middleLatitude = (minimumLatitude + maximumLatitude) / 2
        let stretch = cos(middleLatitude * .pi / 180)
        let width = (maximumLongitude - minimumLongitude) * stretch
        let height = maximumLatitude - minimumLatitude
        guard width > 0, height > 0 else { return nil }

        let projected = raw.map { ring in
            ring.map { point in
                CGPoint(
                    x: (point[0] - minimumLongitude) * stretch / width,
                    y: (maximumLatitude - point[1]) / height
                )
            }
        }
        return Silhouette(rings: projected, aspectRatio: width / height)
    }

    struct Silhouette: Sendable {
        /// Unit-space rings: x and y in 0...1, y growing downward.
        let rings: [[CGPoint]]
        let aspectRatio: Double
    }
}

/// One region's landmass, drawn quietly.
struct ContinentSilhouetteView: View {
    let code: String
    var opacity: Double = 0.45

    var body: some View {
        if let silhouette = ContinentSilhouettes.shipped.silhouette(forDeckCode: code) {
            Canvas { context, size in
                // Fit the unit shape into the frame, centred, aspect kept.
                let scale = min(size.width / silhouette.aspectRatio, size.height)
                let drawnWidth = scale * silhouette.aspectRatio
                let offsetX = (size.width - drawnWidth) / 2
                let offsetY = (size.height - scale) / 2

                var path = Path()
                for ring in silhouette.rings {
                    guard let first = ring.first else { continue }
                    path.move(
                        to: CGPoint(
                            x: offsetX + first.x * drawnWidth, y: offsetY + first.y * scale
                        )
                    )
                    for point in ring.dropFirst() {
                        path.addLine(
                            to: CGPoint(
                                x: offsetX + point.x * drawnWidth,
                                y: offsetY + point.y * scale
                            )
                        )
                    }
                    path.closeSubpath()
                }
                context.fill(path, with: .color(.white.opacity(opacity)))
            }
            .accessibilityHidden(true)
        }
    }
}
