import CoreLocation
import Foundation

/// The country outlines the details map draws, keyed by flag slug.
///
/// The source is Natural Earth's 1:110m admin-0 set (public domain), matched
/// to the bundled flags by the asset slug — the same identifier the flags are
/// keyed by, which is what makes the match survive a localised display name.
/// Generated by `ios/Scripts/generate-country-boundaries.py`.
///
/// Not every flag has an outline: the 1:110m scale carries no microstates and
/// no small islands, so Malta or Nauru resolve to nothing and their sheet
/// simply shows no map. An absent outline is a fact about the source's scale,
/// not an error.
struct CountryBoundaries: Sendable {
    /// Outer rings, one per landmass, in coordinate order.
    struct Outline: Sendable {
        let rings: [[CLLocationCoordinate2D]]
        let center: CLLocationCoordinate2D
        /// The span that fits every ring, padded enough that the outline does
        /// not touch the card's edge.
        let latitudeDelta: Double
        let longitudeDelta: Double
    }

    static let shipped = CountryBoundaries()

    private let rings: [String: [[[Double]]]]

    init(bundle: Bundle = .module) {
        guard
            let url = bundle.url(forResource: "CountryBoundaries", withExtension: "json"),
            let data = try? Data(contentsOf: url),
            let decoded = try? JSONDecoder().decode([String: [[[Double]]]].self, from: data)
        else {
            rings = [:]
            return
        }
        rings = decoded
    }

    func outline(forSlug slug: String) -> Outline? {
        guard let raw = rings[slug], !raw.isEmpty else { return nil }
        let converted = raw.map { ring in
            ring.map { CLLocationCoordinate2D(latitude: $0[1], longitude: $0[0]) }
        }

        let points = converted.flatMap { $0 }
        guard var minimumLatitude = points.first?.latitude else { return nil }
        var maximumLatitude = minimumLatitude
        var minimumLongitude = points[0].longitude
        var maximumLongitude = minimumLongitude
        for point in points {
            minimumLatitude = min(minimumLatitude, point.latitude)
            maximumLatitude = max(maximumLatitude, point.latitude)
            minimumLongitude = min(minimumLongitude, point.longitude)
            maximumLongitude = max(maximumLongitude, point.longitude)
        }

        var center = CLLocationCoordinate2D(
            latitude: (minimumLatitude + maximumLatitude) / 2,
            longitude: (minimumLongitude + maximumLongitude) / 2
        )
        var longitudeDelta = maximumLongitude - minimumLongitude
        // A country crossing the antimeridian — Russia, Fiji — has a naive box
        // the width of the world and a center on the wrong side of it. The
        // mean longitude of the largest ring is where the country mostly is,
        // and a fixed span is honest enough at this scale.
        if longitudeDelta > 180 {
            let largest = converted.max { $0.count < $1.count } ?? converted[0]
            center.longitude =
                largest.reduce(0) { $0 + $1.longitude } / Double(largest.count)
            longitudeDelta = 35
        }

        // Framed wide on purpose: the question the map answers is not "what
        // does the country look like" but "where in the world is it", and
        // that needs the neighbours in the frame.
        return Outline(
            rings: converted,
            center: center,
            latitudeDelta: max((maximumLatitude - minimumLatitude) * 3, 8),
            longitudeDelta: max(longitudeDelta * 3, 8)
        )
    }
}
