import CoreLocation
import Foundation

/// The country outlines the details map draws, keyed by flag slug.
///
/// The source is Natural Earth's 1:10m admin-0 sets (public domain),
/// simplified per ring to a tolerance tied to its own span, matched to the
/// bundled flags by the asset slug: the same identifier the flags are keyed
/// by, which is what makes the match survive a localised display name.
/// Generated by `ios/Scripts/generate-country-boundaries.py`.
///
/// A country carries two geometries, because MapKit's fill and stroke have
/// different limits and one closed ring cannot serve both: closed `fill`
/// polygons for the tint — pre-clipped to web-Mercator's latitudes and split
/// into bands where a shape would be wider than MapKit will draw — and
/// `coast` lines for the stroke, which are real shoreline and nothing else.
/// For every country but Antarctica the two are the same rings, and the
/// stored file carries the coast only where it differs.
struct CountryBoundaries: Sendable {
    struct Outline: Sendable {
        /// Closed polygons for the tint. Never stroked: a fill may be split
        /// along invisible seams a stroke would expose.
        let fills: [[CLLocationCoordinate2D]]
        /// The real coastlines, for the stroke. A closed line is a ring; an
        /// open one is a shoreline that stops at the projection's floor.
        let coasts: [[CLLocationCoordinate2D]]
        /// Whether the map should draw the trace at all. Natural Earth's
        /// remote islets are digitised from old charts and sit kilometres
        /// off the imagery — Bouvet's hexagon floated beside Bouvet. Under
        /// half a degree the camera framing already answers "where is it",
        /// and a wrong trace is worse than none.
        let isTraced: Bool
        let center: CLLocationCoordinate2D
        /// The span that fits every ring, padded enough that the outline does
        /// not touch the card's edge.
        let latitudeDelta: Double
        let longitudeDelta: Double

        /// The same outline with the trace withheld: how the special-areas
        /// deck is drawn, whatever its members' size.
        func untraced() -> Outline {
            Outline(
                fills: fills,
                coasts: coasts,
                isTraced: false,
                center: center,
                latitudeDelta: latitudeDelta,
                longitudeDelta: longitudeDelta
            )
        }
    }

    static let shipped = CountryBoundaries()

    private struct Shape: Decodable {
        let fill: [[[Double]]]
        /// Absent for the countries whose coast is the fill itself.
        let coast: [[[Double]]]?
    }

    private let shapes: [String: Shape]

    init(bundle: Bundle = .module) {
        guard
            let url = bundle.url(forResource: "CountryBoundaries", withExtension: "json"),
            let data = try? Data(contentsOf: url),
            let decoded = try? JSONDecoder().decode([String: Shape].self, from: data)
        else {
            shapes = [:]
            return
        }
        shapes = decoded
    }

    func outline(forSlug slug: String) -> Outline? {
        guard let shape = shapes[slug], !shape.fill.isEmpty else { return nil }
        let fills = shape.fill.map(Self.coordinates)
        let coasts = (shape.coast ?? shape.fill).map(Self.coordinates)

        // The frame is measured off the coast: it is the country's true
        // extent, while a fill may carry clip chords at the projection's
        // floor that are not places anybody means to look at.
        let points = coasts.flatMap { $0 }
        guard var minimumLatitude = points.first?.latitude else { return nil }
        var maximumLatitude = minimumLatitude
        var minimumLongitude = points[0].longitude
        var maximumLongitude = minimumLongitude
        for point in points {
            minimumLatitude = min(minimumLatitude, point.latitude)
            maximumLatitude = max(maximumLatitude, point.latitude)
            minimumLongitude = min(minimumLongitude, point.longitude)
            maximumLongitude = max(maximumLongitude, point.longitude)
        }

        var center = CLLocationCoordinate2D(
            latitude: (minimumLatitude + maximumLatitude) / 2,
            longitude: (minimumLongitude + maximumLongitude) / 2
        )
        var longitudeDelta = maximumLongitude - minimumLongitude
        // A country crossing the antimeridian — Russia, Fiji — has a naive box
        // the width of the world and a center on the wrong side of it. The
        // mean longitude of the largest ring is where the country mostly is,
        // and a fixed span is honest enough at this scale.
        if longitudeDelta > 180 {
            let largest = coasts.max { $0.count < $1.count } ?? coasts[0]
            center.longitude =
                largest.reduce(0) { $0 + $1.longitude } / Double(largest.count)
            longitudeDelta = 35
        }

        // Framed wide on purpose: the question the map answers is not "what
        // does the country look like" but "where in the world is it", and
        // that needs the neighbours in the frame. Capped as well as floored:
        // Antarctica and Russia span so much latitude that three times their
        // height is most of the projection, and the camera lost the country.
        return Outline(
            fills: fills,
            coasts: coasts,
            isTraced: max(
                maximumLatitude - minimumLatitude,
                maximumLongitude - minimumLongitude
            ) >= 0.4,
            center: center,
            latitudeDelta: min(max((maximumLatitude - minimumLatitude) * 3, 8), 60),
            longitudeDelta: max(longitudeDelta * 3, 8)
        )
    }

    private static func coordinates(of ring: [[Double]]) -> [CLLocationCoordinate2D] {
        ring.map { CLLocationCoordinate2D(latitude: $0[1], longitude: $0[0]) }
    }
}
